/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 110918
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 110919
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 110920
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 110921
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 110922
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 110923
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 110924
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 110925
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 110926
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncrOpt.sh 110927
