/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 120121
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 120122
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 120123
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 120124
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 120125
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 120126
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 120127
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 120128
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 120129
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncr.sh 120130
/home/blacklight/solrmarc-sw/examples/stanford/scripts/pullThenIndexSirsiIncrOpt.sh 120131
